WebApplication3/Models/Cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.PresClienUsus = new HashSet<PresClienUsu>();
            this.Prestamos = new HashSet<Prestamo>();
        }
    
        public long Id { get; set; }
        public string ApyNom { get; set; }
        public string Domicilio { get; set; }
        public string DomicilioSec { get; set; }
        public string DNI { get; set; }
        public string Celular { get; set; }
        public string Fijo { get; set; }
        public string Email { get; set; }
        public Nullable<float> Cartera { get; set; }
        public Nullable<long> IdZona { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Zona Zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresClienUsu> PresClienUsus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamos { get; set; }
    }
}

WebApplication3/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class ClientesController : Controller
    {
        Servicios.ServiciosClientes _serviciosClientes = new Servicios.ServiciosClientes();
        Servicios.ServicioZona _serviciosZona = new Servicios.ServicioZona();
        // GET: Clientes
        public ActionResult Index()
        {
            var list = _serviciosClientes.traerTodosClientes();
            if (list.Count() != 0)
            {
                return View(list);
            }
            else
            {
                return View();
            }

        }

        // GET: Clientes/Details/5
        public ActionResult Details(long id)
        {
            var editCliente = _serviciosClientes.traerPorId(id);
            return View(editCliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            var list = _serviciosZona.traerTodasZona();            
            ViewBag.ListaZona = new SelectList(list,"Id", "Descripcion");
            return View();
        }

        // POST: Clientes/Create
        [HttpPost]
        public ActionResult Create(Models.Cliente clienteVM)
        {
            try
            {
                var list = _serviciosZona.traerTodasZona();
                ViewBag.ListaZona = new SelectList(list, "Id", "Descripcion");
                _serviciosClientes.InsertarCliente(clienteVM);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(ex);
            }
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(long id)
        {
            var list = _serviciosZona.traerTodasZona();
            ViewBag.ListaZona = new SelectList(list, "Id", "Descripcion");
            var editCliente = _serviciosClientes.traerPorId(id);
            return View(editCliente);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public ActionResult Edit(Models.Cliente clienteVM)
        {
            try
            {
                _serviciosClientes.EditarCliente(clienteVM);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(long id)
        {
            var deleteCliente = _serviciosClientes.traerPorId(id);
            return View(deleteCliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public ActionResult Delete(Models.Cliente clienteVM)
        {
            try
            {
                _serviciosClientes.BorrarCliente(clienteVM.Id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication3/Controllers/PrestamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class PrestamosController : Controller
    {
        Servicios.ServiciosClientes _serviciosClientes = new Servicios.ServiciosClientes();
        Servicios.ServicioTipoInteres _servicioTipoInteres = new Servicios.ServicioTipoInteres();
        Servicios.ServiciosPrestamo _serviciosPrestamo = new Servicios.ServiciosPrestamo();
        // GET: Prestamos
        public ActionResult Index()
        {
            return View();
        }

        // GET: Prestamos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Prestamos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Prestamos/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Prestamos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Prestamos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Prestamos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Prestamos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult CrearPrestamoConCliente(long id)
        {
            var cliente = _serviciosClientes.traerPorId(id);
            ViewBag.IdZona = cliente.IdZona;
            var listaInteres = _servicioTipoInteres.traerInteres(); 
            var listaCuotas = _servicioTipoInteres.traerCuotas();
            ViewBag.TipoInteres = new SelectList(listaInteres, "Id", "Descripcion");
            ViewBag.TipoCuotas = new SelectList(listaCuotas, "Id", "Descripcion");
            ViewBag.ClienteId = cliente.Id;
            ViewBag.Cliente = cliente.ApyNom;
            return View();
        }
        [HttpPost]
        public ActionResult CrearPrestamoConCliente(Models.Prestamo prestamo)
        {
            _serviciosPrestamo.InsertarPrestamos(prestamo);
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Views/Clientes/Create.cshtml
@model WebApplication3.Models.Cliente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Cliente Nuevo</h2>
@{
    var listadoZona = ViewBag.ListaZona;
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApyNom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApyNom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApyNom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Domicilio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DomicilioSec, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DomicilioSec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DomicilioSec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fijo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fijo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cartera, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cartera, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cartera, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdZona, "IdZona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdZona", listadoZona as SelectList, new { @class = "form-data" })
                @Html.ValidationMessageFor(model => model.IdZona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista de Clientes", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/Clientes/Delete.cshtml
@model WebApplication3.Models.Cliente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar Cliente</h2>

<h3>Esta seguro que desea borrar este Item?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApyNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApyNom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Domicilio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DomicilioSec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DomicilioSec)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fijo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fijo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cartera)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cartera)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zona.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zona.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista de Clientes", "Index")
        </div>
    }
</div>

WebApplication3/Views/Clientes/Details.cshtml
@model WebApplication3.Models.Cliente

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApyNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApyNom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Domicilio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DomicilioSec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DomicilioSec)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fijo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fijo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cartera)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cartera)
        </dd>        

        <dt>
            @Html.DisplayNameFor(model => model.Zona.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zona.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

WebApplication3/Views/Clientes/Edit.cshtml
@model WebApplication3.Models.Cliente

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Cliente</h2>
@{
    var listadoZona = ViewBag.ListaZona;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ApyNom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApyNom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApyNom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Domicilio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DomicilioSec, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DomicilioSec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DomicilioSec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fijo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fijo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cartera, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cartera, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cartera, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdZona, "IdZona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdZona", listadoZona as SelectList, new { @class = "form-data" })
                @Html.ValidationMessageFor(model => model.IdZona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista de Clientes", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/Clientes/Index.cshtml
@model IEnumerable<WebApplication3.Models.Cliente>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Clientes</h2>

<p>
    @Html.ActionLink("Crear Nuevo Cliente", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApyNom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Domicilio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DomicilioSec)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DNI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fijo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cartera)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zona.Descripcion)
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApyNom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Domicilio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DomicilioSec)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DNI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Celular)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fijo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cartera)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zona.Descripcion)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Borrar", "Delete", new { id = item.Id })
                    @Html.ActionLink("Prestamo", "CrearPrestamoConCliente","Prestamos", new { id = item.Id }, null )
                </td>
            </tr>
        }
    }

</table>